# Generated by Django 5.1.4 on 2026-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='教材名稱')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('link', models.URLField(blank=True, verbose_name='連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='上課日期')),
                ('time_start', models.TimeField(verbose_name='開始時間')),
                ('time_end', models.TimeField(verbose_name='結束時間')),
                ('status', models.CharField(choices=[('scheduled', '已排定'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='狀態')),
                ('planned_content', models.TextField(verbose_name='預計進度')),
                ('reminders', models.TextField(blank=True, verbose_name='提醒事項')),
                ('actual_content', models.TextField(blank=True, verbose_name='實際上課內容')),
                ('teacher_note', models.TextField(blank=True, verbose_name='老師備註')),
                ('materials', models.ManyToManyField(blank=True, related_name='sessions', to='core.material', verbose_name='教材')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['-date', '-time_start'],
            },
        ),
    ]
