# Generated by Django 5.1.4 on 2026-03-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='學生名稱')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='學生自訂名稱')),
                ('access_key', models.CharField(max_length=8, unique=True, verbose_name='加入密鑰')),
                ('joined', models.BooleanField(default=False, verbose_name='已加入')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '學生',
                'verbose_name_plural': '學生',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.student', verbose_name='指定學生（空白=共用）'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.student', verbose_name='學生'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.TextField(help_text='請描述您的教學背景或上課證明', verbose_name='上課證明')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已審核')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '老師',
                'verbose_name_plural': '老師',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.teacherprofile', verbose_name='老師'),
        ),
        migrations.AddField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.teacherprofile', verbose_name='老師'),
        ),
    ]
